In [4]:
# by Joh Schöneberg 2019

%matplotlib inline
import sys
import os

pythonPackagePath = os.path.abspath('../src/')
sys.path.append(pythonPackagePath)
from peak_local_max_3d import peak_local_max_3d 

import numpy as np
import pims
import skimage
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [5]:
image = skimage.external.tifffile.imread('../test_data/cropped_master_0000_20pxPadding_frame1.tif')
peaks = image >11000
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(np.nonzero(peaks)[0],np.nonzero(peaks)[1],np.nonzero(peaks)[2],alpha = 0.1)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/johannesschoeneberg/git/JohSchoeneberg/pyLattice_tutorials/test_data/cropped_master_0000_20pxPadding_frame1.tif'

In [7]:
maxima = peak_local_max_3d(image,min_distance=10)

In [8]:
print(maxima)

[[ 4 19 23]
 [10 16 11]
 [11 27 28]
 [16 10 27]
 [22 14 23]
 [23 28 21]]


In [ ]:
peaks = image >11000
maxima = peak_local_max_3d(peaks,min_distance=3)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(np.nonzero(peaks)[0],np.nonzero(peaks)[1],np.nonzero(peaks)[2],alpha = 0.1)
# plot the max coordinates
ax.scatter(maxima[:,0],maxima[:,1],maxima[:,2],c='red')
#ax.view_init(30, 0)